version:  '3'
services:
  jupyter-pyspark:
    # image: jupyter/pyspark-notebook:spark-3.2.1
    build:
      context: custom_image/jupyter-spark
      dockerfile: Dockerfile
    container_name: jupyter-pyspark
    ports:
      - "8085:8888"
      - "8090:4040"
    restart: always
    volumes:
      - "../airflow/:/home/jovyan/"

networks:
  default:
    external: true
    name: waterQ
