version:  '3'
services:
  jupyter-pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-pyspark
    ports:
      - "8085:8888"
      - "8090:4040"
    restart: always
    volumes:
      - "../deployment/notebook:/home/jovyan/"
