name: Run Unit test cases

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  run_test_script:
    runs-on: ubuntu-latest
    steps:
      - name: running test
        run: |
          make run-unit-tests 